export const signUpTranslations = {
  title: "إنشاء حساب",
  subtitle: "إنشاء حساب SmartBox الخاص بك",
  nameLabel: "الاسم الكامل",
  namePlaceholder: "أدخل اسمك الكامل",
  emailLabel: "البريد الإلكتروني",
  emailPlaceholder: "أدخل بريدك الإلكتروني",
  passwordLabel: "كلمة المرور",
  passwordPlaceholder: "إنشاء كلمة مرور",
  phoneLabel: "رقم الهاتف",
  phonePlaceholder: "أدخل رقم هاتفك",
  countryLabel: "البلد",
  countryPlaceholder: "أدخل بلدك",
  imageLabel: "صورة الملف الشخصي (اختياري)",
  imagePlaceholder: "اختر صورة",
  roleLabel: "نوع الحساب",
  rolePlaceholder: "اختر نوع حسابك",
  roles: {
    user: "مستخدم",
    admin: "مدير",
    employee: "موظف",
  },
  accessKeyLabel: "مفتاح الوصول",
  accessKeyPlaceholder: "أدخل مفتاح الوصول",
  accessKeyDescription: "مفتاح الوصول مطلوب لحسابات المدير والموظف",
  signUpButton: "إنشاء حساب",
  hasAccount: "لديك حساب بالفعل؟",
  signInLink: "تسجيل الدخول",
  errors: {
    nameRequired: "الاسم مطلوب",
    emailRequired: "البريد الإلكتروني مطلوب",
    emailInvalid: "يرجى إدخال بريد إلكتروني صحيح",
    passwordRequired: "كلمة المرور مطلوبة",
    passwordMinLength: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
    phoneRequired: "رقم الهاتف مطلوب",
    phoneInvalid: "يرجى إدخال رقم هاتف صحيح",
    countryRequired: "البلد مطلوب",
    roleRequired: "يرجى اختيار نوع الحساب",
    accessKeyRequired: "مفتاح الوصول مطلوب لهذا النوع من الحسابات",
    accessKeyInvalid: "مفتاح الوصول غير صحيح",
    emailExists: "يوجد مستخدم بهذا البريد الإلكتروني بالفعل",
    networkError: "حدث خطأ في الشبكة",
  },
  success: {
    signUpSuccess: "تم إنشاء الحساب بنجاح",
  },
} as const;

export type SignUpTranslations = typeof signUpTranslations;
