export const signUpTranslations = {
  title: 'Sign Up',
  subtitle: 'Create your SmartBox account',
  nameLabel: 'Full Name',
  namePlaceholder: 'Enter your full name',
  emailLabel: 'Email',
  emailPlaceholder: 'Enter your email',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Create a password',
  phoneLabel: 'Phone Number',
  phonePlaceholder: 'Enter your phone number',
  countryLabel: 'Country',
  countryPlaceholder: 'Enter your country',
  imageLabel: 'Profile Image (Optional)',
  imagePlaceholder: 'Choose an image',
  roleLabel: 'Account Type',
  rolePlaceholder: 'Select your account type',
  roles: {
    user: 'User',
    admin: 'Admin',
    employee: 'Employee',
  },
  accessKeyLabel: 'Access Key',
  accessKeyPlaceholder: 'Enter access key',
  accessKeyDescription: 'Access key is required for admin and employee accounts',
  signUpButton: 'Sign Up',
  hasAccount: 'Already have an account?',
  signInLink: 'Sign in',
  errors: {
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Please enter a valid phone number',
    countryRequired: 'Country is required',
    roleRequired: 'Please select an account type',
    accessKeyRequired: 'Access key is required for this account type',
    accessKeyInvalid: 'Invalid access key',
    emailExists: 'User with this email already exists',
    networkError: 'Network error occurred',
  },
  success: {
    signUpSuccess: 'Account created successfully',
  },
} as const;

export type SignUpTranslations = typeof signUpTranslations;
