export default {
  productPage: {
    title: 'تفاصيل المنتج',
    addToCart: 'أضف للسلة',
    outOfStock: 'نفد المخزون',
    inStock: 'متوفر',
    description: 'الوصف',
    specifications: 'المواصفات',
    reviews: 'المراجعات',
    writeReview: 'اكتب مراجعة',
    reply: 'رد',
    submit: 'إرسال',
    relatedProducts: 'منتجات ذات صلة',
    chooseColor: 'اختر اللون:',
    chooseStorage: 'اختر السعة:',
    share: 'مشاركة',
  },
  breadcrumbs: {
    home: 'الرئيسية',
    category: 'الفئة',
    products: 'المنتجات',
  },
  reviews: {
    verifiedPurchase: 'شراء موثق',
    likes: 'إعجابات',
    replyButton: 'رد',
    ratingLabel: 'التقييم',
    emptyReviews: 'لا توجد مراجعات بعد. كن أول من يراجع!',
    yourRating: 'تقييمك',
    yourName: 'اسمك',
    yourEmail: 'بريدك الإلكتروني',
    yourReview: 'مراجعتك',
    writeReply: 'اكتب رداً...',
    submitReply: 'إرسال الرد',
    cancel: 'إلغاء',
    nameRequired: 'الاسم مطلوب',
    emailRequired: 'البريد الإلكتروني مطلوب',
    emailInvalid: 'بريد إلكتروني غير صالح',
    ratingRequired: 'يرجى اختيار تقييم',
    reviewRequired: 'المراجعة مطلوبة (10 أحرف على الأقل)',
    reviewMinLength: 'يجب أن تكون المراجعة 10 أحرف على الأقل',
    reviewMaxLength: 'يجب أن تكون المراجعة أقل من 1000 حرف',
    replyRequired: 'الرد مطلوب (10 أحرف على الأقل)',
    sortBy: 'ترتيب حسب:',
    newest: 'الأحدث',
    highest: 'الأعلى تقييماً',
    lowest: 'الأقل تقييماً',
    allRatings: 'كل التقييمات',
    star: 'نجمة',
    stars: 'نجوم',
  },
  gallery: {
    hoverToZoom: 'تكبير',
    imageCounter: '{current} / {total}',
  },
  info: {
    sku: 'رمز المنتج:',
    brand: 'العلامة التجارية:',
    category: 'الفئة:',
    quantity: 'الكمية:',
    freeShipping: 'شحن مجاني',
    warranty: 'ضمان لمدة عام',
    returns: 'إرجاع خلال 30 يوم',
  },
  specs: {
    specifications: 'المواصفات',
    weight: 'الوزن',
    dimensions: 'الأبعاد',
  },
  sharing: {
    facebook: 'فيسبوك',
    twitter: 'تويتر',
    whatsapp: 'واتساب',
    copyLink: 'نسخ الرابط',
    copied: 'تم النسخ!',
  },
  related: {
    youMayAlsoLike: 'قد يعجبك أيضاً',
  },
};
