export default {
  productPage: {
    title: 'Product Details',
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    description: 'Description',
    specifications: 'Specifications',
    reviews: 'Reviews',
    writeReview: 'Write a Review',
    reply: 'Reply',
    submit: 'Submit',
    relatedProducts: 'Related Products',
    chooseColor: 'Choose Color:',
    chooseStorage: 'Choose Storage:',
    share: 'Share',
  },
  breadcrumbs: {
    home: 'Home',
    category: 'Category',
    products: 'Products',
  },
  reviews: {
    verifiedPurchase: 'Verified Purchase',
    likes: 'Likes',
    replyButton: 'Reply',
    ratingLabel: 'Rating',
    emptyReviews: 'No reviews yet. Be the first to review!',
    yourRating: 'Your Rating',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourReview: 'Your Review',
    writeReply: 'Write a reply...',
    submitReply: 'Submit Reply',
    cancel: 'Cancel',
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Invalid email address',
    ratingRequired: 'Please select a rating',
    reviewRequired: 'Review is required (minimum 10 characters)',
    reviewMinLength: 'Review must be at least 10 characters long',
    reviewMaxLength: 'Review must be less than 1000 characters',
    replyRequired: 'Reply is required (minimum 10 characters)',
    sortBy: 'Sort by:',
    newest: 'Newest',
    highest: 'Highest Rating',
    lowest: 'Lowest Rating',
    allRatings: 'All Ratings',
    star: 'Star',
    stars: 'Stars',
  },
  gallery: {
    hoverToZoom: 'Hover to zoom',
    imageCounter: '{current} / {total}',
  },
  info: {
    sku: 'SKU:',
    brand: 'Brand:',
    category: 'Category:',
    quantity: 'Quantity:',
    freeShipping: 'Free Shipping',
    warranty: '1 Year Warranty',
    returns: '30-Day Returns',
  },
  specs: {
    specifications: 'Specifications',
    weight: 'Weight',
    dimensions: 'Dimensions',
  },
  sharing: {
    facebook: 'Facebook',
    twitter: 'Twitter',
    whatsapp: 'WhatsApp',
    copyLink: 'Copy Link',
    copied: 'Copied!',
  },
  related: {
    youMayAlsoLike: 'You May Also Like',
  },
};
