export const addProductDictionary = {
  title: "إضافة منتج جديد",
  subtitle: "قم بإنشاء قائمة منتجات جديدة في متجرك",
  productName: "اسم المنتج",
  productBasicInfo: "المعلومات الأساسية",
  description: "الوصف",
  category: "الفئة",
  brand: "الماركة",
  price: "السعر",
  discount: "الخصم",
  stock: "كمية المخزون",
  sku: "رمز SKU",
  images: "صور المنتج",
  specifications: "المواصفات",
  save: "حفظ المنتج",
  cancel: "إلغاء",
  active: "حالة النشاط",
  add: "إضافة",
};
