export const addProductDictionary = {
  title: "Add New Product",
  subtitle: "Create a new product listing in your store",
  productName: "Product Name",
  productBasicInfo: "Basic Information",
  description: "Description",
  category: "Category",
  brand: "Brand",
  price: "Price",
  discount: "Discount",
  stock: "Stock Quantity",
  sku: "SKU",
  images: "Product Images",
  specifications: "Specifications",
  save: "Save Product",
  cancel: "Cancel",
  active: "Active Status",
  add: "Add",
};
